### ISSUE TITLE
Think for the proper host name for the site (and domain too)

### ISSUE THREAD

**Issue by dangoriaynov** [UkrSoft/choose-operator#21]
We need to think over the options for the host name of our site

**Comment by Tendzin** [comment]
На основе списка возможных доменов и цены -  https://www.ukraine.com.ua/
Предлагаю **in.ua** - дешево и подходит под нашу цель (именно для операторов Украины)

Имя:
- bestoperator.in.ua (bestmobile.in.ua)
- selectoperator.in.ua (selectmobile.in.ua)
- youroperator.in.ua
- mobileoperator.in.ua
- mobile.in.ua (operator.in.ua)

Предлагайте свои варианты, выберем лучший.

**Comment by dangoriaynov** [comment]
bestoperator.in.ua is available and costs 4$
However I think we should take shorter name like: 
- [ ] boo.in.ua (best operator online in ua)
- [ ] oper.in.ua
- [x] ~~operator.in.ua~~
- [x] ~~best.in.ua~~
- [x] ~~ukrsoft.ua~~

And even some cyrillic domains (10.68 $):
- [ ] мійоператор.укр
- [ ] хочу-оператор.укр
- [ ] улюбленець.укр
- [ ] кращий-оператор.укр

and even!
- [ ] моя-няшка.укр

**Comment by dangoriaynov** [comment]
You may check your own variants here: https://www.ukraine.com.ua/domains/

**Comment by dangoriaynov** [comment]
Ok. our host will be http://boo.in.ua
This domain was already bought today.
