### ISSUE TITLE
[DataBase] Only one parameter (offer, packge or operator) should be populated in Feature field

### ISSUE THREAD

**Issue by Tendzin** [UkrSoft/choose-operator#29]
Create logic for population only one parameter. Fields offer, packge or operator can have null value

**Comment by dangoriaynov** [comment]
mmm...maybe we could just disable ability to create features from their separate page on admin site?
I think features should be created as inlines from package, offer or operator admin pages.

Also it's not clear for me what is the use case for operator to have feature...

**Comment by dangoriaynov** [comment]
Feature.operator field doesn't exist in current model. Please review the model and close ticket as offer-package population validation was already implemented in **features/choose-operator-24**
