### ISSUE TITLE
[DataBase] Create attributes in attr table (localhost)

### ISSUE THREAD

**Issue by Tendzin** [UkrSoft/choose-operator#34]
Number of minutes, num  of mess, topBand, traffic and connection price (for calls)

**Comment by dangoriaynov** [comment]
And also - don't forget to add description to each attribute - for what it is used.
..because one day we could get lost...

**Comment by dangoriaynov** [comment]
This should be organically linked with new table **Units**. Please review current data in DB and then close this ticket
