### ISSUE TITLE
[Question] How can we populate DurationField in Admin?

### ISSUE THREAD

**Issue by Tendzin** [UkrSoft/choose-operator#37]
Дан, привет.
Подскажи, есть ли смысл в таблице Period использовать поле DurationField? Насколько вижу по описанию, это отличная замена просто Integer.
И как описать заполнение такого поля в Admin.

**Comment by dangoriaynov** [comment]
I don't think this is good solution - this field should store real timeframe bound to real dates.
Look at the Django [docs](https://docs.djangoproject.com/en/1.8/ref/models/fields/#durationfield)
And description of timedelta type on [Python docs](https://docs.python.org/3/library/datetime.html#available-types)

**Comment by dangoriaynov** [comment]
I think we could leave this part of model intact.
