### ISSUE TITLE
[DataBase] Add rule for required only one field from couple

### ISSUE THREAD

**Issue by Tendzin** [UkrSoft/choose-operator#38]
Example: 
One of the next fields should be populated in Payment table: feature_id or offer_id. There should be created rule for population of this fields.

Another fields that also should be populated in such way will be mark as todo with apropriate number of ticket.

**Comment by dangoriaynov** [comment]
This should help:
http://stackoverflow.com/questions/24802244/custom-validation-in-django-admin

**Comment by dangoriaynov** [comment]
Also if you realize that you need this logic implemented elsewhere - please see [this](https://docs.djangoproject.com/en/1.8/ref/models/fields/#validators)

**Comment by dangoriaynov** [comment]
fixed in features/choose-operator-24
